/* tslint:disable */
/* eslint-disable */
/**
 * Agent service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AgentsList
 */
export interface AgentsList {
    /**
     * 
     * @type {string}
     * @memberof AgentsList
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentsList
     */
    lastName?: string;
    /**
     * 
     * @type {number}
     * @memberof AgentsList
     */
    sold?: number;
}

export function AgentsListFromJSON(json: any): AgentsList {
    return AgentsListFromJSONTyped(json, false);
}

export function AgentsListFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentsList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'FirstName') ? undefined : json['FirstName'],
        'lastName': !exists(json, 'LastName') ? undefined : json['LastName'],
        'sold': !exists(json, 'Sold') ? undefined : json['Sold'],
    };
}

export function AgentsListToJSON(value?: AgentsList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'FirstName': value.firstName,
        'LastName': value.lastName,
        'Sold': value.sold,
    };
}


